export const WAGER_MARKET_ADDRESS = '0x0629464b2ecA0C6F7CB1412EC9a40FC3da8550f3' as const

export const WAGER_MARKET_ABI = [
  // Public state variables
  {
    inputs: [],
    name: 'totalVolume',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalResolved',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalVoided',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalProtocolFees',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalStakerFees',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalPayouts',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalStandardWagers',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalPriceBets',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'openWagerCount',
    outputs: [{ type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  // Functions
  {
    inputs: [],
    name: 'getOpenWagers',
    outputs: [{ type: 'uint256[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'wagerId', type: 'uint256' }],
    name: 'getWagerDetails',
    outputs: [
      {
        components: [
          { name: 'id', type: 'uint256' },
          { name: 'creator', type: 'address' },
          { name: 'wagerType', type: 'uint8' },
          { name: 'amount', type: 'uint256' },
          { name: 'odds', type: 'uint256' },
          { name: 'expiresAt', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'winner', type: 'address' },
          { name: 'createdAt', type: 'uint256' },
          { name: 'resolvedAt', type: 'uint256' },
        ],
        name: 'wager',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ name: 'user', type: 'address' }],
    name: 'getUserFeeInfo',
    outputs: [
      {
        components: [
          { name: 'protocolFeePercent', type: 'uint256' },
          { name: 'stakerFeePercent', type: 'uint256' },
          { name: 'totalFeePercent', type: 'uint256' },
        ],
        name: 'feeInfo',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { name: 'description', type: 'string' },
      { name: 'eventDate', type: 'uint256' },
      { name: 'depositWindow', type: 'uint256' },
      { name: 'creatorStake', type: 'uint256' },
      { name: 'challengerStake', type: 'uint256' },
      { name: 'challengerAddress', type: 'address' },
      { name: 'category', type: 'uint8' },
    ],
    name: 'createWager',
    outputs: [{ name: 'wagerId', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
  {
    inputs: [
      { name: 'description', type: 'string' },
      { name: 'tokenId', type: 'uint256' },
      { name: 'targetPrice', type: 'uint256' },
      { name: 'isAbove', type: 'bool' },
      { name: 'creatorStake', type: 'uint256' },
      { name: 'challengerAddress', type: 'address' },
    ],
    name: 'createPriceBet',
    outputs: [{ name: 'wagerId', type: 'uint256' }],
    stateMutability: 'payable',
    type: 'function',
  },
] as const
